services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - ${PROMTAIL_PORT:-9080}:9080
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
      - ./storage/monitoring/promtail:/var/lib/promtail
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - monitoring
      - shared-network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - ${LOKI_PORT:-3100}:3100
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/local-config.yml
    networks:
      - monitoring
      - shared-network

  ### Warn sudo chown -R 65534:65534 ./storage/monitoring/prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./storage/monitoring/prometheus:/prometheus
    networks:
      - monitoring
      - shared-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - ${GRAFANA_PORT:-3030}:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - ./monitoring/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./storage/monitoring/grafana:/var/lib/grafana
    networks:
      - monitoring
      - shared-network

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)
    ports:
      - ${NODE_EXPORTER_PORT:-9100}:9100
    networks:
      - monitoring
      - shared-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - ${CADVISOR_PORT:-8080}:8080
    networks:
      - monitoring
      - shared-network

networks:
  monitoring:
    driver: bridge
  shared-network:
    external: true
    name: shared-network

volumes:
  grafanadata:
  prometheusdata: