version: '3'

services:
  # node_app:
  #   container_name: node_app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   networks:
  #     - chat_network
  #   depends_on:
  #     - redis-stack

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - chat_network
    environment:
      REDIS_ARGS: "--requirepass secret"
    restart: always

networks:
  chat_network: